// Define the control that will contain the chart
var chartControl = L.Control.extend({
  options: {
    position: 'topright',
    backgroundColor: 'rgba(255, 255, 255, 0.6)'
  },
  onAdd: function (map) {
    // Create the container for the chart
    var container = L.DomUtil.create('div', 'leaflet-bar leaflet-control leaflet-control-custom');
    container.id = 'chart-container';
    container.style.backgroundColor = this.options.backgroundColor;
    // Add the chart element to the container
    var chartElement = document.getElementById('chart');
    container.appendChild(chartElement);
    //container.style.opacity = 1;
    // Prevent clicks on the chart from propagating to the map
    L.DomEvent.disableClickPropagation(container);

    return container;
  }
});

// Set up the Leaflet map
var map = L.map('map', {zoomControl: false}).setView([52.5200, 13.4050], 4);

map.addControl(new chartControl());

// Add the tile layer (map tiles from OpenStreetMap)
L.tileLayer('https://{s}.basemaps.cartocdn.com/rastertiles/light_all/{z}/{x}/{y}.png', {
        minZoom: 0,
        maxZoom: 10,
        tms: false,
        attribution: 'Generated by TilesXYZ'
}).addTo(map);

L.control.zoom({
    position: 'bottomleft'
}).addTo(map);

L.tileLayer('./no2_tiles/{z}/{x}/{y}.png', {
  minZoom: 0,
  maxZoom: 10,
  maxNativeZoom: 6,
  opacity: 0.6,
  tms: false
}).addTo(map);
